take_care:
  shot_for_me:
    - I can see it in your eyes, you're angry
    - Regret got shit on what you're feelin' now
    - Mad cause he ain't like me
    - Oh you mad cause nobody ever did it like me
    - All the care I would take
    - All the love that we made
    - Now you're trying to find somebody to replace what I gave to you
    - It's a shame you didn't keep it
    - Alisha, Catya, I know that you gon' hear this
    - I'm the man, yeah I said it
    - Bitch, I'm the man, don't you forget it
    - The way you walk, that's me
    - The way you talk, that's me
    - The way you've got your hair up, did you forget that's me?
    - And the voice in your speaker right now that's me
    - That's me, and the voice in your ear
    - That's me, can't you see
    - That I made it?
    - Yeah, I made it
    - First I made you who you are and then I made it
    - And you're wasted with your latest
    - Yeah, I'm the reason why you always getting faded
    - Take a shot for me, oh oh oh oh
    - Take a shot for me
    - A shot for me
    - Ok, look, I'm honest
    - Girl I can't lie I miss you
    - You and the music were the only things that I'd commit to
    - I never cheated, for the record, back when I was with you
    - But you believed in everything but me
    - Girl, I don't get you
    - She says I know you changed
    - I never see you cause you're always busy doing things
    - I really wish she had a different way of viewing things
    - I think the city that we're from just kinda ruined things
    - It's such a small place
    - not much to do but talk and listen
    - The men are jealous and the women all in competition
    - And all your friends telling you stories that you often misinterpret
    - And taint all the images of your Mr. Perfect
    - I could tell that you been crying all night, drinking all summer
    - Praying for your happiness
    - Hope that you recover
    - This is one I know you hated when you heard it
    - And it's worse because you know that I deserve it
views:
  one_dance:
    - Grips on your waist
    - Front way, back way
    - You know that I don't play
    - Streets not safe
    - But I never run away
    - Even when I'm away
    - Oti, oti, there's never much love when we go OT
    - I pray to make it back in one piece
    - I pray, I pray
    - That's why I need a one dance
    - Got a Hennessy in my hand
    - One more time 'fore I go
    - Higher powers taking a hold on me
    - Got a pretty girl and she love me long time
    - Wine it, wine it, very long time
    - Oh, yeah, she steady on grindin'
    - Back up, back up and wine it, girl
    - Tell me, I need to know, where do you wanna go?
    - Cause if you're down, I'll take it slow
    - Make you lose control
    - Where, where, where
    - Where, where, where, where
if_youre_reading_this_its_too_late:
  6_god:
    - Watch your motherfuckin' tone boy
    - Get hurt boy
    - Aww here go another mo'fucker that don't understand the concept of puttin' money first boy
    - I'm 'bout to hit you with the work boy
    - I hate comin' through stuntin' on people that I know, ahh that's the worst boy
    - You haven't been a man for like a minute
    - I told you that I'm in it for the long haul
    - You can really get the business
    - I'll admit it, I'll admit it
    - You too worried 'bout the bitches
    - I got one girl, and she my girl, and nobody else can hit it
    - She'll admit it, she'll admit it
    - She ain't fuckin' with you people
    - And just like every single other thing in my life
    - You can have her when I'm finished
    - I hear the talk on road is I'm the shit boy
    - Phone call back home, shit is hot up in the 6 boy
    - Shit hot up in the 6 right now shit hot up in the 6 boy
    - Shit is hot up in the 6 right now
    - Come see us and get it fixed boy
    - Black Benz on the road boy
    - Already had a Rolls Royce
    - Sold a couple Bentley last week, them were my old toys
    - I give a fuck about old boy
    - I give a fuck about his squad boy
    - I give a fuck about your mob boy
    - I'm the real 6 God boy
    - I'm about to say a true thing
    - You was poppin' back when Usher wore a U-chain
    - God damn you changed
    - I put it on 'erything, it's a err ting
    - It's a OVO come through murk things
    - I know you heard things
    - Bitch I know you heard things
    - Yeah, I know you heard things
    - Nobody really likes us except for us
    - Yeah, all I ever needed was the squad so that's what's up
    - Yeah, my sound got the whole city a way right now
    - So I don't give a fuck about what anybody sayin' right now
nothing_was_the_same:
  started_from_the_bottom:
    - Started from the bottom now we're here
    - Started from the bottom now my whole team f-bomb here
    - I done kept it real from the jump
    - Living at my mama's house we'd argue every mornin
    - I was trying to get it on my own
    - Working all night, traffic on the way home
    - And my uncle calling me like Where ya at
    - I gave you the keys told ya bring it right back
    - I just think it's funny how it goes
    - Now I'm on the road, half a million for a show
    - Boys tell stories about the man
    - Say I never struggled, wasn't hungry, yeah, I doubt it
    - I could turn your boy into the man
    - There ain't really much I hear that's poppin' off without us
    - We just want the credit where it's due
    - I'mma worry about me, give a f-bomb about you
    - Just as a reminder to myself
    - I wear every single chain, even when I'm in the house
    - F-bomb a fake friend, where you real friends at
    - Story stayed the same through the money and the fame
  hold_on_were_going_home:
    - I got my eyes on you
    - You're everything that I see
    - I want your high love and emotion endlessly
    - I can't get over you
    - You left your mark on me
    - I want your high love and emotion endlessly
    - You're the girl
    - You're the one
    - Gave you everything I love
    - I think there's something, baby
    - Cause you're a good girl and you know it
    - You act so different around me
    - Cause you're a good girl and you know it
    - I know exactly who you could be
    - Just hold on we're going home
    - It's hard to do these things alone
    - Just hold on we're going home