thank_me_later:
  over:
    - Bottles on me
    - Long as someone drink it
    - Never drop the ball
    - F!ck y'all thinking?
    - Making sure the young money ship is never sinking
    - Bout to set it off in this bitch Jada Pinkett
    - I shouldn't have drove
    - Tell me how I'm getting home
    - You too fine to be laying down in bed alone
    - I can teach you how to speak my language Rosetta stone
    - I swear this life is like the sweetest thing I've ever known
    - About to go thriller Mike Jackson on these playas
    - All I need is a fucking red jacket with some zippers
    - Super good smidoke a package of the Swishers
    - I did it overnight
    - It couldn't happen any quicker
    - Y'all know them? But f!ck it me either
    - But point the biggest skeptic out I'll make them a believer
    - It wouldn't be the first time I've done it
    - Throwing hundreds
    - When I should be throwing ones bitch I run it ah
    - I know way too many people here right now that I didn't know last year
    - Who the f!ck are y'all?
    - I swear it feels like the last few nights we've been everywhere and back but
    - I just can't remember it all
    - What am I doing?
    - Oh, yeah, that's right. I'm doing me
    - I'm doing me
    - I'm living life right now
    - And this what I'mma do 'til it's over
    - Til it's over
    - And it's far from over
    - One thing 'bout music when it hits you feel no pain
    - And I swear I got this shit that makes these bitches go insane
    - So they tell me that they love me
    - I know better than that it's just game
    - It's just what comes with the fame
    - And I'm ready for that
    - I'm just saying
    - I really can't complain
    - Everything is kosher
    - Two thumbs up, ebert and roeper
    - I really can't see the end getting any closer
    - But I'll probably still be the man when everything is over
    - So I'm riding through the city with my high beams on
    - Can you see me? Can you see me? Get your Visine on
    - Y'all just do not fit the picture
    - Turn your widescreen on
    - If you thinking I'mma quit before I die dream on
    - Man, they treat me like a legend
    - Am I really this cold
    - I'm really too young to be feeling this old
    - It's about time you admit it
    - Who you kidding, man? Nobody's ever done it like I did it
so_far_gone:
  best_i_ever_had:
    - You know a lot of girls be
    - Thinking my songs about them
    - This is not to get confused
    - This ones for you
    - Baby you're my everything
    - You're all I ever wanted
    - We could do it real big
    - Bigger than you ever done it
    - You be up on everything
    - Other hoes ain't ever on it
    - I want this forever
    - I swear I could spend whatever on it
    - Cause she hold me down every time I hit her up
    - When I get right I promise that we gone live it up
    - She make me beg for it
    - Till she give it up
    - And I say the same thing every single time
    - I say you the f!ckin' best
    - You the best I ever had
    - I say you the f!ckin'
    - Know you gotta roommate
    - Call me when there's no one there
    - Put the key under the mat 
    - You know I be over there
    - I be over there
    - Shawty I be over there
    - I be hittin' all the spots that you ain't even know was there
    - And you don't even have to ask twice
    - You could have my heart
    - Or we could share it like the last slice
    - Always felt like you were so accustomed to the fast life
    - Have a playa thinking that he met you in a past life
    - Sweat pants, hair tied
    - Chillin with no make-up on
    - That's when you're the prettiest, I hope that you don't take it wrong
    - You don't even trip when friends say you ain't bringing Drake along
    - You know that I'm working I be there soon as I make it home
    - And she a patient in my waiting room,
    - Never pay attention to the rumours and what they assume
    - And until em' girls prove it, I'm the one that never get confused wit
    - Sex, love, pain
    - Baby I be on that Tank shit
    - Buzz so big, I could probably sell a blank disk
    - Play my album, drop bitches will buy it for the picture
    - And playas will buy two and claim they got it for they sister
    - Magazine paper girl but money ain't the issue
    - They bring dinner to my room and ask me to initial
    - She call me the referee cause I be so official
    - My shirt ain't got no stripes but I can make your pussy whistle
    - Like the Andy Griffith theme song
    - And who told you to put them jeans on
    - Double cup love, you're the one I lean on
    - Feeling for a fix, than you should really get your fiend on
    - Yeah, just know my condo is the crack spot
    - Every single show she out there reppin' like a mascot
    - Get it from the back and make ya f!ckin' bra strap pop
take_care:
  shot_for_me:
    - I can see it in your eyes, you're angry
    - Regret got shit on what you're feelin' now
    - Mad cause he ain't like me
    - Oh you mad cause nobody ever did it like me
    - All the care I would take
    - All the love that we made
    - Now you're trying to find somebody to replace what I gave to you
    - It's a shame you didn't keep it
    - Alisha, Catya, I know that you gon' hear this
    - I'm the man, yeah I said it
    - Bitch, I'm the man, don't you forget it
    - The way you walk, that's me
    - The way you talk, that's me
    - The way you've got your hair up, did you forget that's me?
    - And the voice in your speaker right now that's me
    - That's me, and the voice in your ear
    - That's me, can't you see
    - That I made it?
    - Yeah, I made it
    - First I made you who you are and then I made it
    - And you're wasted with your latest
    - Yeah, I'm the reason why you always getting faded
    - Take a shot for me, oh oh oh oh
    - Take a shot for me
    - A shot for me
    - Ok, look, I'm honest
    - Girl I can't lie I miss you
    - You and the music were the only things that I'd commit to
    - I never cheated, for the record, back when I was with you
    - But you believed in everything but me
    - Girl, I don't get you
    - She says I know you changed
    - I never see you cause you're always busy doing things
    - I really wish she had a different way of viewing things
    - I think the city that we're from just kinda ruined things
    - It's such a small place
    - not much to do but talk and listen
    - The men are jealous and the women all in competition
    - And all your friends telling you stories that you often misinterpret
    - And taint all the images of your Mr. Perfect
    - I could tell that you been crying all night, drinking all summer
    - Praying for your happiness
    - Hope that you recover
    - This is one I know you hated when you heard it
    - And it's worse because you know that I deserve it
views:
  one_dance:
    - Grips on your waist
    - Front way, back way
    - You know that I don't play
    - Streets not safe
    - But I never run away
    - Even when I'm away
    - Oti, oti, there's never much love when we go OT
    - I pray to make it back in one piece
    - I pray, I pray
    - That's why I need a one dance
    - Got a Hennessy in my hand
    - One more time 'fore I go
    - Higher powers taking a hold on me
    - Got a pretty girl and she love me long time
    - Wine it, wine it, very long time
    - Oh, yeah, she steady on grindin'
    - Back up, back up and wine it, girl
    - Tell me, I need to know, where do you wanna go?
    - Cause if you're down, I'll take it slow
    - Make you lose control
    - Where, where, where
    - Where, where, where, where
if_youre_reading_this_its_too_late:
  6_god:
    - Watch your motherfuckin' tone boy
    - Get hurt boy
    - Aww here go another mo'fucker that don't understand the concept of puttin' money first boy
    - I'm 'bout to hit you with the work boy
    - I hate comin' through stuntin' on people that I know, ahh that's the worst boy
    - You haven't been a man for like a minute
    - I told you that I'm in it for the long haul
    - You can really get the business
    - I'll admit it, I'll admit it
    - You too worried 'bout the bitches
    - I got one girl, and she my girl, and nobody else can hit it
    - She'll admit it, she'll admit it
    - She ain't fuckin' with you people
    - And just like every single other thing in my life
    - You can have her when I'm finished
    - I hear the talk on road is I'm the shit boy
    - Phone call back home, shit is hot up in the 6 boy
    - Shit hot up in the 6 right now shit hot up in the 6 boy
    - Shit is hot up in the 6 right now
    - Come see us and get it fixed boy
    - Black Benz on the road boy
    - Already had a Rolls Royce
    - Sold a couple Bentley last week, them were my old toys
    - I give a fuck about old boy
    - I give a fuck about his squad boy
    - I give a fuck about your mob boy
    - I'm the real 6 God boy
    - I'm about to say a true thing
    - You was poppin' back when Usher wore a U-chain
    - God damn you changed
    - I put it on 'erything, it's a err ting
    - It's a OVO come through murk things
    - I know you heard things
    - Bitch I know you heard things
    - Yeah, I know you heard things
    - Nobody really likes us except for us
    - Yeah, all I ever needed was the squad so that's what's up
    - Yeah, my sound got the whole city a way right now
    - So I don't give a fuck about what anybody sayin' right now
nothing_was_the_same:
  started_from_the_bottom:
    - Started from the bottom now we're here
    - Started from the bottom now my whole team f-bomb here
    - I done kept it real from the jump
    - Living at my mama's house we'd argue every mornin
    - I was trying to get it on my own
    - Working all night, traffic on the way home
    - And my uncle calling me like Where ya at
    - I gave you the keys told ya bring it right back
    - I just think it's funny how it goes
    - Now I'm on the road, half a million for a show
    - Boys tell stories about the man
    - Say I never struggled, wasn't hungry, yeah, I doubt it
    - I could turn your boy into the man
    - There ain't really much I hear that's poppin' off without us
    - We just want the credit where it's due
    - I'mma worry about me, give a f-bomb about you
    - Just as a reminder to myself
    - I wear every single chain, even when I'm in the house
    - F-bomb a fake friend, where you real friends at
    - Story stayed the same through the money and the fame
  hold_on_were_going_home:
    - I got my eyes on you
    - You're everything that I see
    - I want your high love and emotion endlessly
    - I can't get over you
    - You left your mark on me
    - I want your high love and emotion endlessly
    - You're the girl
    - You're the one
    - Gave you everything I love
    - I think there's something, baby
    - Cause you're a good girl and you know it
    - You act so different around me
    - Cause you're a good girl and you know it
    - I know exactly who you could be
    - Just hold on we're going home
    - It's hard to do these things alone
    - Just hold on we're going home